### ISSUE TITLE
cannot join Uint8Array - broken in Safari 9 and IE10

### ISSUE THREAD

**Issue by csillery** [metafizzy/huebee#10]
![screensnapz041](https://cloud.githubusercontent.com/assets/636151/22118225/f3a3fb48-de44-11e6-918f-da31dedc342d.png)

**Comment by HackedBeat** [comment]
Temporary solution:
Add this line to the top of your code
**Uint8ClampedArray.prototype.join = [].join;**

PS: My patch that fixes this problem still awaiting consideration by the author.

**Comment by csillery** [comment]
Thanks, man.

**Comment by dustineichler** [comment]
I'm seeing this in Firefox too. `Uint8ClampedArray.prototype.join = Array.prototype.join;` fixes this as mentioned above.

**Comment by desandro** [comment]
Thank you for reporting this bug. I'll look to resolve this issue during my next development run on Huebee.

**Comment by desandro** [comment]
v1.0.1 has been released with a fix for this bug. Thank you for your input!
