### ISSUE TITLE
Prevent Keyboard fomr appearing in ios

### ISSUE THREAD

**Issue by mimeArtist** [metafizzy/huebee#11]
I've had a look at the documentation, but can't see it listed... is there a way of preventing the keyboard appearing at the same time as the picker?

**Comment by mimeArtist** [comment]
I found a solution that works for me at least — put readonly="true" in your input field.

**Comment by mimeArtist** [comment]
...or actually just putting readonly seems to be the best method.

**Comment by desandro** [comment]
This is an accessibility issue. You should be able to type in the color. `readonly` may be a suitable hack
