### ISSUE TITLE
Add Huebee to Composer

### ISSUE THREAD

**Issue by cole007** [metafizzy/huebee#14]

**Comment by desandro** [comment]
Huebee is not available on Composer at this time. But I'm happy to consider it.

**Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by cole007** [comment]
That would be great. Using Huebee in a #Craftcms plugin at https://github.com/cole007/crafthuebee and be good to not depend on manually updating the codebase with updates.

Thanks for a great add-on!

**Comment by desandro** [comment]
I have chosen not to support Composer. Thank you for this request. Sorry to pass on this one.
