### ISSUE TITLE
Incorrect width with using hues

### ISSUE THREAD

**Issue by DenVys** [metafizzy/huebee#17]
i initialize huebee in html 
if i change number of hues ( `<input class="color-input" data-huebee  data-huebee='{ "hues": "1" }'/>` )
the width of element become very huge
![huebee_bug](https://user-images.githubusercontent.com/36623192/45518417-193c9180-b7ba-11e8-8f49-3607b44cd70d.jpg)
(width - 2000px on pic)

**Comment by desandro** [comment]
whoa! That's definitely a bug. Thanks for reporting this. I'll have to take a look.

**Comment by desandro** [comment]
Ah, thanks for the PR. Rather than converting strings to integers, you could just set the value as an integer `"hues": 1`. This is valid JSON

``` html
<input class="color-input" data-huebee='{ "hues": 1 }'/>
```

**Comment by DenVys** [comment]
ohh, i'm sorry. my bad. but anyway i think it's better to check
