### ISSUE TITLE
Incorrect hue when modding colours

### ISSUE THREAD

**Issue by AllanPinheiroDeLima** [metafizzy/huebee#21]
I'm using HueBee with angular and I have come across a weird bug.

**Actual Behavior**
Everytime I select an color from pink or red hues, they come as negative hues, as shown in print

**Expected Behavior**:

Hues must be in range of 0 to 360

**Reproduction steps**
Install HueBee and print the actual color in the console after selecting a hue from pink to red in the right side of the picker panel

I'm sending a print of the problem
![image](https://user-images.githubusercontent.com/20716785/57329976-388e8300-70eb-11e9-985e-b1ef8b17ebb2.png)

Am I doing something wrong ?

**Comment by desandro** [comment]
Thanks for reporting this issue. Do you have a live URL or *reduced test case* I could look at? I'm not able to debug the issue from the screenshot.
