### ISSUE TITLE
IsLight is undefined

### ISSUE THREAD

**Issue by Nounours13** [metafizzy/huebee#24]
For isLight functionality you must change at ligne 896 :

this.emitEvent( 'change', [ color, swatch.hue, swatch.sat, swatch.lum ] );

By

this.emitEvent( 'change', [ color, swatch.hue, swatch.sat, swatch.lum, this.isLight ] );

**Comment by desandro** [comment]
You can access [`isLight`](http://huebee.buzz/#properties) from the instance, so you don't need to add to add another argument.
