### ISSUE TITLE
Set input text color to bg color on change?

### ISSUE THREAD

**Issue by wbelk** [metafizzy/huebee#28]
Is there a way to set input text color to bg color on change?

For example, I want the text to be the same color as the selected swatch, so that it's invisible to the viewer. I.e. they only see the swatch with no text.

Or maybe there is a way to set the text color to transparent?

**Comment by wbelk** [comment]
I was able to achieve this by wrapping with a `<div><span open hueb.open() on click, give me color></span><input hubee hide me always></div>`

![Screen Recording 2020-08-27 at 07 28 28 PM](https://user-images.githubusercontent.com/271844/91514543-dfc49a00-e89b-11ea-87a8-9375dc490a93.gif)

**Comment by desandro** [comment]
Thanks for following up. You don't have to use Huebee on an input. You can use it on a <div> then use a the [change event](https://huebee.buzz/#events) to set a hidden <input> to that value
