### ISSUE TITLE
Add ability to set font and border color too

### ISSUE THREAD

**Issue by tvb** [metafizzy/huebee#29]
Hi, I would like to set the font color and border color of elements too with Huebee. I know I can do it with the` .on('change')` event, but it would be nice if we would get native support with something like `setFont` and `setBorder` configuration parameters.

**Comment by tvb** [comment]
Anyone?

**Comment by desandro** [comment]
Thanks for this feature request. This kind of feature is exactly what the `change` event is designed for. the `setBGColor` and  `setText` options are good defaults to style the UI element. All other possibilities can be handled through the `change` event.
