### ISSUE TITLE
Custom Colors Only

### ISSUE THREAD

**Issue by coreyworrell** [metafizzy/huebee#5]
Hi, I did not notice a way to use only custom colors. This can be very handy when you wish to limit selection to a brand's color theme or similar.

Thank you.

**Comment by desandro** [comment]
**Add a 👍  reaction** to this issue if you would like to see Huebee support only `customColors` with no grid of hues & saturations.

Thank you for this feature request!

**Comment by gregblass** [comment]
Removing the grey pallet on the right would be great too.

**Comment by desandro** [comment]
Huebee v2.1.0 has been released with support for this feature. See [`customColors`](https://huebee.buzz/#customcolors)

> Set shades: 0 to disable normal colors and use only custom colors. Use hues to set the number of columns.

``` js
customColors: [ '#C25', '#E62', '#EA0', '#ED0', '#6C6', '#19F', '#258', '#333' ],
shades: 0,
hues: 4,
```

![image](https://user-images.githubusercontent.com/85566/80025727-15e9ab80-84af-11ea-87d6-d3f33ff243a4.png)

Please update and report back with any issues. Thank you for your patience with this one 🐝
